### ISSUE TITLE
Add custom control

### ISSUE THREAD

**Issue by reinvanleirsberghe** [WiredSolutions/react-azure-maps#28]
Is and how is it possible to add a custom control? https://azuremapscodesamples.azurewebsites.net/Custom%20Modules/Bring%20Data%20Into%20View%20Control/Bring%20Data%20Into%20View%20Control.html

**Comment by msasinowski** [comment]
Currently, we support only base controls on the map the list is here https://github.com/WiredSolutions/react-azure-maps/blob/19633f6e2bc2db6d3a6bbecb7b1989516820884e/src/components/AzureMap/useCreateMapControls.tsx#L20

We try to add this in 0.0.2 as regular option in `AzureMapComponent` , or you can always take the ref from AzureMapContext 

`const { mapRef } = useContext<IAzureMapsContextProps>(AzureMapsContext)`

And just add another control like in the example https://github.com/Azure-Samples/AzureMapsCodeSamples/blob/master/AzureMapsCodeSamples/Custom%20Modules/Bring%20Data%20Into%20View%20Control/Bring%20Data%20Into%20View%20Control.html

**Comment by srednicki95** [comment]
@reinvanleirsberghe Thanks for your proposal. Feel free to add more.
This feature will appear soon in version 0.0.2.
You can find implementation of custom control in Playground
[https://github.com/WiredSolutions/react-azure-maps-playground/tree/master/src/examples/CustomControl](url)
