### ISSUE TITLE
No implementation of bubble layer?

### ISSUE THREAD

**Issue by onionhammer** [WiredSolutions/react-azure-maps#29]
Not sure what else is missing, but this one stands out

**Comment by msasinowski** [comment]
@onionhammer 
`export type IAzureMapLayerType =
  | 'SymbolLayer'
  | 'HeatLayer'
  | 'ImageLayer'
  | 'LineLayer'
  | 'PolygonExtrusionLayer'
  | 'PolygonLayer'
  | 'TitleLayer'`

Yes you are right we are missing this in our library, We will try to add this in next version.
