### ISSUE TITLE
AzureMapHtmlMarker 'markerContent' prop 

### ISSUE THREAD

**Issue by orlahowell** [WiredSolutions/react-azure-maps#38]
Looking to change the `markerContent` for `AzureMapHtmlMarker` after initial load, but I can't get it to work - is this something similar to #36?

Thanks for the quick response!

**Comment by msasinowski** [comment]
@orlahowell Yes, it is a similar issue, we won't add this fix in 0.0.4, because there are some differences in implementation for HtmlMarkerPopup and just simple Popup. We will discuss that and work on this and resolve that in 0.0.5.

Thank you for your input 👍
