### ISSUE TITLE
Html markers

### ISSUE THREAD

**Issue by QPRocky** [WiredSolutions/react-azure-maps#47]
Hi, this is not really an issue, but I couldn't find sample from playground samples.
What I'm looking for, is how clustering HTML markers work?
I see, its done on azure maps web SDK but cant figure out, how to archieve it with react-azure-maps

**Comment by srednicki95** [comment]
Thanks for your feedback, we have missing logic with adding HTMLMarker to dataSource. It will be fixed in next release.

Anyway you can still cluster Features and Shapes and is more effectible and have better performance instead of HTMLMarkers

@QPRocky  To be sure we are on the same page: can you add exactly what you want and how you done it on pure azure maps sdk?

**Comment by QPRocky** [comment]
Thanks for reply.
Actually I would like to cluster points like here:
[https://azuremapscodesamples.azurewebsites.net/HTML%20Markers/HtmlMarkerLayer/HTML%20Marker%20Layer.html](HTML Marker Layer)
But instead using build-it markers, I would like to use my own custom images. (at moment managed to use own images with <AzureMapHtmlMarker> component)

**Comment by srednicki95** [comment]
Ok now I see what we need to update. I will update exactly the same example on our playground. I think it should be available tomorrow. Thanks again for feedback and feel free to create another issue if we still have missing some features or you need help

**Comment by QPRocky** [comment]
Wow, very nice!
Thanks!

**Comment by msasinowski** [comment]
**Update:** We still working on that but facing a couple of issues with this custom layer implementation which coming from AzureMapsCodeSamples we will try to solve it somehow.

**Comment by msasinowski** [comment]
@QPRocky feature is done in **0.0.7** example of using this is in https://github.com/WiredSolutions/react-azure-maps-playground/commit/3099420a0d0d1fdc14fdba2125a76dcea33c2150
