### ISSUE TITLE
After Installation getting "ReferenceError: self is not defined"

### ISSUE THREAD

**Issue by DharmendraNaberly** [WiredSolutions/react-azure-maps#53]
![self1](https://user-images.githubusercontent.com/53552327/78535427-feb57900-77a0-11ea-9fed-bf36b9b14885.png)

**Comment by srednicki95** [comment]
@DharmendraNaberly 
Please add more info how you import and use this package?

**Comment by msasinowski** [comment]
**Close the issue.**
**Reason: No proper steps to reproduce.**
