### ISSUE TITLE
Popup components with React hooks don't call hooks or render updates

### ISSUE THREAD

**Issue by smith1511** [WiredSolutions/react-azure-maps#54]
Versions: 
react-azure-maps 0.0.7
react 16.13.0

Problem:
I'm using a AzureMapPopup - when I supply a React component that uses hooks (or classes with async fetching) to popupContent - it renders the initial view but never re-renders the component or calls the Hooks/API.  I believe this could be caused by the use of renderToStaticMarkup in useCreatePopup().

Expect Behavior:
My component uses a Hook to fetch API results.  While waiting for the API response the component renders a loading spinner, then the results.  I only see the loading spinner however, it never actually invokes the hook or re-renders.

When the component is used outside Maps, it works as expected.

**Comment by msasinowski** [comment]
Hello @smith1511 , thanks for reporting the issue.
I think for now there is no way to fix this in an easy way because`renderToStaticMarkup` does not support async rendering. The other thing is that the Popup that is provided by `azure-maps-control` accepts only static HTML string and we need to render it somehow on our side.

The one way to implement that kind of feature is just grabbing an async call from `popupContent` component and put that into a parent component and make sure that `popupContent` not have any async calls.

**Comment by smith1511** [comment]
Thanks for the reply - I feared that.

When you say move the logic to the parent - is there a way to do that so that the API calls are only done when the user clicks on a popup?

In my scenario I have 50-60 HTML markers, and ideally when someone clicks or mouses over one, I only want to load the async content at that point.

What I'm currently doing is pre-loading all content and passing the results into the Map as props - but this is obviously not very performant.

**Comment by smith1511** [comment]
One other thing I noticed is that this seems to prevent the usage of <Link to={...}/> - unless you know a way around that?

**Comment by msasinowski** [comment]
> Thanks for the reply - I feared that.
> 
> When you say move the logic to the parent - is there a way to do that so that the API calls are only done when the user clicks on a popup?
> 
> In my scenario I have 50-60 HTML markers, and ideally when someone clicks or mouses over one, I only want to load the async content at that point.
> 
> What I'm currently doing is pre-loading all content and passing the results into the Map as props - but this is obviously not very performant.

Ok but you can also create a simple state for popup data in the parent component, and whenever someone clicks make an async call, set result in state and use that state in the popup content and this approach should work. It is really hard to help you without some code sample or something like that, so if you can please attach something like that :). Also, I would say that HtmlMarker from `azure-map-controls` may not be the best option for handling this amount of data. @srednicki95

**Comment by msasinowski** [comment]
> One other thing I noticed is that this seems to prevent the usage of `<Link to={...}/>` - unless you know a way around that?

We will check this one.

**Comment by srednicki95** [comment]
@smith1511  We prepared example for you [AsyncPopupExample](https://github.com/WiredSolutions/react-azure-maps-playground/blob/master/src/examples/AsyncPopupExample.tsx)

Fell free to comments if you have any other question?
