### ISSUE TITLE
How to load IAzureDataSourceChildren of type="Polygon"

### ISSUE THREAD

**Issue by ms-sunayak** [WiredSolutions/react-azure-maps#55]
I am trying to create an array of data source children of type polygon. I am not able to follow much from the typing of IAzureDataSourceChildren as i don't see a way to pass the atlas.data.Polygon element by AzureMapFeature props. Any pointers or sample on how to load polygon using AzureDataSourceChildren and AzureMapfeature would help me here. 

![image](https://user-images.githubusercontent.com/61801074/79405544-922d3d80-7f49-11ea-9724-6de2b3063d97.png)

**Comment by msasinowski** [comment]
hello, @ms-sunayak in the `IAzureMapFeature` `type` prop you can pass the following types, so if you set `Polygon` as type it should work fine.

![image](https://user-images.githubusercontent.com/38035075/79541942-0ae7e300-808b-11ea-8396-fa689dca1213.png)

**Comment by srednicki95** [comment]
Hi @ms-sunayak
You can add polygon as AzureMapFeature with type `Polygon` and pass array of coords inside `coordinates` props of that feature. You need to remember to create layer with type `PolygonLayer`.

To add array of polygons you can map inside `<AzureMapDataSourceProvider />` or pass geojson as `collection` props if this is local variable or `dataFromUrl` if you want async download that data.

I also add example with simple polygons [Polygon Example](https://github.com/WiredSolutions/react-azure-maps-playground/blob/master/src/examples/PolygonExample.tsx)
