### ISSUE TITLE
React-native

### ISSUE THREAD

**Issue by cbiras** [WiredSolutions/react-azure-maps#76]
Does this repo work with React native? I need to build a mobile app that works on both Android and iOS so that's why I'm not using the Azure Maps Android Sdk. 
The problem is that when I try to import these two:
```
import {AzureMap, AzureMapsProvider, IAzureMapOptions} from 'react-azure-maps';

import {AuthenticationType} from 'azure-maps-control';
```
it's throwing an Cannot create URL for blob! exception in the react-azure-maps.umd.js and in the atlas.min.js files.

The dependencies installed in package.json are:
```
 "azure-maps-control": "^2.0.31",
    "expo": "~39.0.2",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-azure-maps": "^0.1.4",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-web": "~0.13.7",
    "typescript": "^3.7.5"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
```

**Comment by psrednicki** [comment]
Hi @cbiras 
Azure Map have Android SDK as far. 
We dont tested it on mobile, so probably its wont work.
After MS will add also iOS SDK we can think about it.
