### ISSUE TITLE
npm package 0.1.4 does not match git commit with tag 0.1.4

### ISSUE THREAD

**Issue by bg6471** [WiredSolutions/react-azure-maps#82]
The types file updated in https://github.com/WiredSolutions/react-azure-maps/pull/74 (commit tagged 0.1.4) does not match the one in npm package 0.1.4.

Sample repro:
- npx create-react-app my-app --template typescript
- Change directory to /my-app
- npm i react-azure-maps
- Check node_modules/react-azure-maps/dist/types/types.d.ts - it is not updated

Alternatively download the .tgz directly from npm using link below, extract it, and you'll notice that types.d.ts is still the old version.
https://registry.npmjs.org/react-azure-maps/-/react-azure-maps-0.1.4.tgz

No code changes are required, so there's nothing I can do to help but report the issue. The npm package may need to be re-published.

**Comment by psrednicki** [comment]
Hi @bg6471, I republished package.
